# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-19 16:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Projects'),
        ),
    ]
