# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Projects',
        ),
        migrations.RenameField(
            model_name='activities',
            old_name='product',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='product',
            new_name='project',
        ),
    ]
