# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 15:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Color'),
        ),
        migrations.AddField(
            model_name='activities',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Projects'),
        ),
    ]
