# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_auto_20161005_1034'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.States_kanban')),
            ],
        ),
    ]
