# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161209_1440'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Projects'),
        ),
        migrations.AddField(
            model_name='projects',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Color'),
        ),
    ]
