# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-13 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_department', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Priorities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prioritie', models.CharField(max_length=45)),
                ('order', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_states', models.CharField(max_length=45)),
                ('valid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='States_kanban',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_states', models.CharField(max_length=45)),
                ('color', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=45)),
                ('answer', models.CharField(max_length=45)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_date', models.DateTimeField(blank=True, null=True)),
                ('Customers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Customers')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Departments')),
                ('prioritie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Priorities')),
                ('responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.Contributors')),
                ('states', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.States')),
                ('states_kanban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.States_kanban')),
            ],
        ),
    ]
