# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
