# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-09 20:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='responsable',
            new_name='responsible',
        ),
    ]
