# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date_time',
            field=models.DateTimeField(default=b'CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'),
        ),
    ]
