# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Tasks'),
        ),
        migrations.AddField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Contributors'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='description',
            field=models.TextField(),
        ),
    ]
