# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='Customers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Customers'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Activities'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='answer',
            field=models.CharField(max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Departments'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='prioritie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.Priorities'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='responsible',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='people.Contributors'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='states',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.States'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='states_kanban',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.States_kanban'),
        ),
    ]
