# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161108_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='estimated_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='total_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
