# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161209_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date_time',
        ),
    ]
