# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 21:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161020_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish_date',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
