# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_tasks_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_time',
            field=models.DateTimeField(default=b'CURRENT_TIMESTAMP'),
        ),
    ]
