# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20161025_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
