# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20161103_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish_date',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
