# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 21:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20161110_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='finish_date',
            new_name='date_finish',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='start_date',
            new_name='date_start',
        ),
    ]
