# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-06 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20161206_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='date_time',
            field=models.DateTimeField(default=b'current_timestamp'),
        ),
    ]
