# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-08 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20161104_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish_date',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start_date',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
