# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-10 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20161110_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='date_finish',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='date_start',
        ),
    ]
