# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20161005_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='states_kanban',
            field=models.ForeignKey(blank=True, default=b'Por hacer', null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.States_kanban'),
        ),
    ]
