# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20161005_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
