# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 17:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='position',
            new_name='role',
        ),
    ]
