# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-25 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='role',
            new_name='cargo',
        ),
    ]
