# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20160925_0905'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='contacto1',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='contacto2',
            field=models.CharField(default=9, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='direccion',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customers',
            name='telefono',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contributors',
            name='image_2',
            field=models.ImageField(default='img/icono_perfil.png', upload_to='img/'),
        ),
    ]
