# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20160927_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='image_2',
            field=models.ImageField(default='../static/img/icono_perfil.png', upload_to='img/'),
        ),
    ]
