# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-27 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0005_auto_20160927_1037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='cargo',
            new_name='role',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='direccion',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='contacto1',
            new_name='contact1',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='contacto2',
            new_name='contact2',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='correo',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='telefono',
            new_name='telephone',
        ),
    ]
