# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0006_auto_20160826_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributors',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contributors',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(max_length=50),
        ),
    ]
