# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20160928_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(choices=[('C', 'Colaborador'), ('A', 'Administrador')], max_length=20),
        ),
    ]
