# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0007_auto_20160826_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributors',
            name='image_2',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
