# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-29 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_auto_20160929_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='role',
            field=models.CharField(max_length=20),
        ),
    ]
