# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0008_contributors_image_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributors',
            name='image_2',
            field=models.ImageField(upload_to='img/'),
        ),
    ]
