# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-05 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0009_auto_20160929_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='last_name',
        ),
    ]
