# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0012_auto_20161013_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='image',
            field=models.ImageField(upload_to='imag/'),
        ),
    ]
