# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0014_remove_customers_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='image',
            field=models.ImageField(default='../static/img/icono_perfil.png', upload_to='img/'),
        ),
    ]
