# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0016_auto_20161013_0805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='image',
        ),
    ]
