# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_remove_customers_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='customers',
            table=None,
        ),
    ]
