# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-13 14:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_auto_20161013_0939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={},
        ),
        migrations.AlterModelTable(
            name='customers',
            table='Customers',
        ),
    ]
